ARG DT_RELEASE_VERSION
ARG DT_RELEASE_STAGE
ARG DT_RELEASE_PRODUCT
FROM java:8
EXPOSE 8080
ADD /target/ticket-booking-service-0.0.1-SNAPSHOT.jar ticket-booking-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","ticket-booking-service-0.0.1-SNAPSHOT.jar"]
ENV SOME=ticket-booking-service
